
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PeopleProTraining.Dal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public string FirstName { get; set; }

    public int EmployeeID { get; set; }

    public int DepartmentDepartmentID { get; set; }

    public int BuildingBuildingID { get; set; }

    public string LastName { get; set; }

    public System.DateTime DoB { get; set; }

    public int RoomNumber { get; set; }

    public string Title { get; set; }

    public decimal Salary { get; set; }



    public virtual Building Building { get; set; }

    public virtual Department Department { get; set; }

}

}
